#!/usr/bin/env bash

clean=false
build=false
test=false

while getopts ':cbt' opt ; do
    case "${opt}" in
        'c') clean=true ;;
        'b') build=true ;;
        't') test=true ;;
        *) echo "Invalid option ${OPTARG}" && exit 1 ;;
    esac
done

if "${clean}" ; then
    rm -rf dist types
fi

if "${build}" ; then
    tsc && node dist/test.js && rm dist/test.js types/test.d.ts
fi

if "${test}" ; then
    tsc --noEmit
fi