#!/usr/bin/env bash

# Extract local package name and version and changelog version
package_name="$(npm --silent v ./ name)"
echo "Package Name  = ${package_name}"
local_version="$(npm --silent v ./ version)"
echo "Local Version = ${local_version}"
log_version="$(grep -oE '[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md | head -n1)"
echo "Log Version   = ${log_version}"

# Make sure package.json and changelog versions match
if [[ "${local_version}" != "${log_version}" ]] ; then
    echo 'Package and changelog versions do not match!'
    exit 1
fi

# Compile and test the package
mkdir -p Examples && npx tsc && npx eslint src && node dist/test.js && rm dist/test.js types/test.d.ts && cd example || exit 1

# Run all the examples for the package starting with basic NodeJS examples
for examplejs in *.mjs ; do
    if [ ! -f "${examplejs}" ] ; then
        continue
    fi
    example="${examplejs%.*}"
    projectdir="${example// /_}_demo"
    echo "Running example ${example}..."
    {
        echo "# ${example}"
        cat "${example}.md" || exit 1
        echo
        echo '## Installation'
        echo "Follow these steps to create a new project workspace and install the ${package_name} dependency to run this example."
        echo '```shell'
        echo '# Create and open project folder'
        echo "mkdir ${projectdir}"
        echo "cd ${projectdir}"
        echo '# Initialize project and install dependencies'
        echo 'npm init -y'
        echo "npm i ${package_name}@${local_version}"
        echo '# Create and open source file'
        echo "touch \"${examplejs}\""
        echo "open \"${examplejs}\""
        echo '```'
        echo '## Source'
        echo "Copy and paste this source code into \`${examplejs}\`."
        echo '```js'
        cat "${examplejs}" || exit 1
        echo
        echo '```'
        echo '## Output'
        echo "In \`${projectdir}/\`, execute \`${examplejs}\` with NodeJS to generate an output."
        echo '```shell'
        echo "node \"${examplejs}\""
        echo '```'
        echo 'You should expect to see an output similar to the one below.'
        echo '```text'
        node "${examplejs}" || exit 1
        echo '```'
        echo '<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>'
    } > "../Examples/${example}.md"
done
# Run UI examples with webpack
for exampledir in */ ; do
    if [ ! -d "${exampledir}" ] ; then
        continue
    fi
    # Run and build example
    example="${exampledir%/}"
    projectdir="${example// /_}_demo"
    echo "Running example ${example}..."
    cd "${example}" && npm i && npx webpack --mode development || exit 1
    # Create directory and copy example output
    outpath="_assets/${package_name}/${exampledir}"
    mkdir -p "../../../../${outpath}"
    cp -r index.html dist "../../../../${outpath}"
    # Write example instructions
    {
        echo "# ${example}"
        cat ./*.md || exit 1
        echo
        echo '## Installation'
        echo "Follow these steps to create a new [webpack](https://webpack.js.org/) project and install the ${package_name} dependency to run this example."
        echo '```shell'
        echo '# Create and open project folder'
        echo "mkdir ${projectdir}"
        echo "cd ${projectdir}"
        echo '# Initialize project and install dependencies'
        echo 'npm init -y'
        echo 'npm pkg set type="module"'
        echo "npm i ${package_name}@${local_version} webpack-cli"
        echo '# Create source files'
        echo 'touch index.html'
        echo 'mkdir src'
        echo 'touch src/index.js'
        echo '# Open new files'
        echo 'open index.html'
        echo 'open src/index.js'
        echo '```'
        echo '## Source'
        echo 'Copy and paste the following source code blocks into the newly created files.'
        echo '### index.html'
        echo '```html'
        cat 'index.html' || exit 1
        echo
        echo '```'
        echo '### index.js'
        echo '```js'
        cat 'src/index.js' || exit 1
        echo
        echo '```'
        echo '## Build Project'
        echo "In the base project directory \`${projectdir}/\`, run the following command. If changes are made in the source files, the demo will automatically be recompiled. Press CTRL+C to stop running."
        echo '```shell'
        echo 'npx webpack --mode development --watch'
        echo '```'
        echo '## View Project'
        echo 'Open the `index.html` file in any web browser of your choice! You should see a page similar to the one below.'
        echo "<iframe src=\"../${outpath}/index.html\" width=\"100%\" height=\"600\"></iframe>"
        echo '<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js"></script>'
    } > "../../Examples/${example}.md"
    cd ..
done
